---
title: "Education Levels in Iowa"
output: html_document
---

```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
options(message = FALSE)
```


```{r, echo = FALSE, warning = FALSE, message=FALSE}
rm(list=ls())
library(readr)
packageStartupMessage(library(choroplethr))
packageStartupMessage(library(choroplethrMaps))
library(dplyr)
packageStartupMessage(library(tmap))
packageStartupMessage(library(tmaptools))

packageStartupMessage(library(sf))
packageStartupMessage(library(ggplot2))
packageStartupMessage(library(plotly))
library(ggiraph)

suppressMessages({
  my_map <- st_read("~/Documents/research/primate_map/project_materials/sci_comm/shapefiles/rural_variables.geojson", quiet=TRUE)
})


# my_map <- st_read("~/Documents/research/primate_map/project_materials/sci_comm/shapefiles/rural_variables.geojson")

my_map$cleaned_rural_High.school.graduate..includes.equivalency... <- as.numeric(my_map$cleaned_rural_High.school.graduate..includes.equivalency...)
my_map$cleaned_rural_Bachelor.s.degree.. <- as.numeric(my_map$cleaned_rural_Bachelor.s.degree..)
my_map$cleaned_rural_Graduate.or.professional.degree.. <- as.numeric(my_map$cleaned_rural_Graduate.or.professional.degree..)
```


## High School Graduates  
```{r, echo = FALSE, warning = FALSE, message = FALSE}

my_plot <- ggplot() +
  geom_sf(data = my_map, aes(fill = cleaned_rural_High.school.graduate..includes.equivalency...)) +
  scale_fill_gradientn(colours = c("#f7fcf0", "#084081"), 
                       #breaks = quantile(my_map2$cleaned_grouped_data_import_ratio, probs = seq(0, 1, 0.25)), 
                       na.value = "black", 
                       guide = "legend") +
  theme_void()

# Add hover information using plotly
ggplotly(my_plot, tooltip = c("cleaned_rural_High.school.graduate..includes.equivalency..."))


```


## Bachelor's Degree Holders
```{r, echo = FALSE, warning = FALSE, message = FALSE}

my_plot2 <- ggplot() +
  geom_sf(data = my_map, aes(fill = cleaned_rural_Bachelor.s.degree..)) +
  scale_fill_gradientn(colours = c("#f7fcf0", "#084081"), 
                       #breaks = quantile(my_map2$cleaned_grouped_data_import_ratio, probs = seq(0, 1, 0.25)), 
                       na.value = "black", 
                       guide = "legend") +
  theme_void()

# Add hover information using plotly
ggplotly(my_plot2, tooltip = c("cleaned_rural_Bachelor.s.degree.."))

```

## Graduate Degree Holders
```{r, echo = FALSE, warning = FALSE, message = FALSE}

my_plot3 <- ggplot() +
  geom_sf(data = my_map, aes(fill = cleaned_rural_Graduate.or.professional.degree..)) +
  scale_fill_gradientn(colours = c("#f7fcf0", "#084081"), 
                       #breaks = quantile(my_map2$cleaned_grouped_data_import_ratio, probs = seq(0, 1, 0.25)), 
                       na.value = "black", 
                       guide = "legend") +
  theme_void()

# Add hover information using plotly
ggplotly(my_plot3, tooltip = c("cleaned_rural_Graduate.or.professional.degree.."))

```







